# Generated by Django 3.0.8 on 2020-07-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='empty', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='imagePath',
            field=models.CharField(default='empty', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='empty', max_length=300),
            preserve_default=False,
        ),
    ]
