# Generated by Django 3.0.8 on 2020-07-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_is_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_ordered',
        ),
    ]
